# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Lifegame < Formula
  desc "Conway's game of life for tui"
  homepage "https://github.com/crcrworks/lifegame"
  url "https://github.com/crcrworks/lifegame/archive/refs/tags/v0.1.2.tar.gz"
  sha256 "c773367b771050aa8e5c3a1fce1abde69114559933c1511e7941188516ac98f3"

  def install
    bin.install "{{ env.PROJECT_NAME }}-v0.1.3-aarch64-unknown-linux-musl" => "{{ env.PROJECT_NAME }}"
  end
end
